### ISSUE TITLE
Duplicate saved windows (redux)

### ISSUE THREAD

**Issue by jonathaneunice** [Connorhd/TabCloud#2]
The issue of "Duplicate saved windows" https://github.com/Connorhd/TabCloud/issues/closed#issue/1 is still very much an open/important issue. 

Github says I "closed" it. If I did, it was pilot error, and completely unintentional. I haven't been able to figure out how to re-open it. So this stub is here to keep the issue alive.

**Comment by Connorhd** [comment]
Not sure what happened, I've reopened the old one.
