### ISSUE TITLE
No middle-click avaliable on my laptop

### ISSUE THREAD

**Issue by smaglio81** [Connorhd/TabCloud#6]
I have a laptop which doesn't have a middle-click. Is there another way to open up single saved page?

**Comment by Connorhd** [comment]
You should be able to hold ctrl and click.

**Comment by smaglio81** [comment]
That worked. Thanks!

On Wed, Apr 11, 2012 at 1:06 PM, Connor Dunn <
reply@reply.github.com

> wrote:
> 
> You should be able to hold ctrl and click.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Connorhd/TabCloud/issues/6#issuecomment-5077756

## 

Steven Maglio
smaglio81@gmail.com
twitter: http://twitter.com/smaglio81
linkedin: http://www.linkedin.com/in/stevenmaglio
tech-blog: http://stevenmaglio.blogspot.com/
